import { PairRule } from "@/types";

// Complete Thai Numerology Dictionary for 2-digit combinations (00-99)
export const PAIR_RULES_MAP: Record<string, PairRule> = {
  // === คู่มงคลระดับสูงสุด (A+ TIER) ===
  "14": {
    pair: "14",
    tier: "A+",
    scoreDelta: 18,
    category: "การเจรจา / ปัญญา",
    title: "คู่เจรจาเป็นเลิศ ผู้ใหญ่เมตตา",
    meaning: "พูดจาน่าเชื่อถือ เข้าหาผู้ใหญ่ได้ดี มีวาทศิลป์ งานวิชาการ การติดต่อประสานงานโดดเด่น",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 9, prestige: 7, wisdom: 9, luck: 8 },
  },
  "41": {
    pair: "41",
    tier: "A+",
    scoreDelta: 18,
    category: "การเจรจา / ปัญญา",
    title: "คู่ปัญญาเจรจา วาทศิลป์ดึงดูดทรัพย์",
    meaning: "มีปฏิภาณไหวพริบ ความจำดี ผู้ใหญ่ให้ความช่วยเหลือ ติดต่อค้าขายสำเร็จง่าย",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 9, prestige: 7, wisdom: 9, luck: 8 },
  },
  "15": {
    pair: "15",
    tier: "A+",
    scoreDelta: 20,
    category: "สติปัญญา / มิตรผู้ใหญ่",
    title: "คู่มหาปัญญา ผู้ใหญ่อุปถัมภ์ค้ำชู",
    meaning: "มีความสุขุม รอบคอบ จิตใจมั่นคง ซื่อสัตย์ มีเกียรติยศ เจริญก้าวหน้าในหน้าที่การงาน",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 8, prestige: 9, wisdom: 10, luck: 9 },
  },
  "51": {
    pair: "51",
    tier: "A+",
    scoreDelta: 20,
    category: "สติปัญญา / มิตรผู้ใหญ่",
    title: "คู่บารมีปัญญา เจริญรุ่งเรือง",
    meaning: "ได้รับความเมตตาจากเจ้านายและผู้ใหญ่ มีโชคเรื่องการเรียน การสอบ และการเลื่อนตำแหน่ง",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 8, prestige: 9, wisdom: 10, luck: 9 },
  },
  "24": {
    pair: "24",
    tier: "A+",
    scoreDelta: 20,
    category: "มหาเสน่ห์ / เมตตามหานิยม",
    title: "คู่เสน่ห์มหานิยม ค้าขายร่ำรวย",
    meaning: "เสน่ห์แรง คนรักใคร่เอ็นดู เจรจาค้าขายดีเลิศ มีเงินทองไหลมาเทมาไม่ขาดมือ สุภาพอ่อนโยน",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 10, prestige: 7, wisdom: 8, luck: 9 },
  },
  "42": {
    pair: "42",
    tier: "A+",
    scoreDelta: 20,
    category: "มหาเสน่ห์ / เมตตามหานิยม",
    title: "คู่เมตตา มหาโภคทรัพย์",
    meaning: "วาจาเป็นทรัพย์ มีคนช่วยเหลือซัพพอร์ตตลอดเวลา เพื่อนฝูงรักใคร่ การเงินคล่องตัวสูง",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 10, prestige: 7, wisdom: 8, luck: 9 },
  },
  "28": {
    pair: "28",
    tier: "A+",
    scoreDelta: 17,
    category: "เงินก้อนโต / นักลงทุน",
    title: "คู่มังกรเงินก้อนใหญ่ ใจใหญ่ หมุนเงินหลักล้าน",
    meaning: "จับเงินก้อนโต วิสัยทัศน์กว้างไกล เหมาะกับเจ้าของกิจการ นักลงทุน อสังหาฯ เล่นหุ้น",
    caution: "ใช้เงินเก่ง ใจใหญ่ ต้องมีคู่สติคุม (เช่น 15/51/59)",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 7, prestige: 9, wisdom: 6, luck: 9 },
  },
  "82": {
    pair: "82",
    tier: "A+",
    scoreDelta: 17,
    category: "เงินก้อนโต / นักลงทุน",
    title: "คู่เศรษฐีเงินก้อน บริหารเงินหมุนเวียน",
    meaning: "มีเซ้นส์ทางการเงิน คุมลูกน้องได้ดี ทำธุรกิจสเกลใหญ่ โครงการใหญ่สำเร็จ",
    caution: "ระวังเรื่องใจอ่อนให้คนยืมเงิน",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 7, prestige: 9, wisdom: 6, luck: 9 },
  },
  "36": {
    pair: "36",
    tier: "A+",
    scoreDelta: 19,
    category: "เสน่ห์ดึงดูดทรัพย์ / ความรัก",
    title: "คู่เสน่ห์ขยันรวย การเงินและความรักสมบูรณ์",
    meaning: "ขยันขันแข็ง หาเงินเก่ง เสน่ห์ดึงดูดทั้งเพศตรงข้ามและลูกค้า ความรักสดใส มีความกระตือรือร้น",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 10, prestige: 7, wisdom: 7, luck: 9 },
  },
  "63": {
    pair: "63",
    tier: "A+",
    scoreDelta: 19,
    category: "เสน่ห์ดึงดูดทรัพย์ / ความรัก",
    title: "คู่ขยันรับทรัพย์ เสน่ห์แรง เงินเข้าหลายทาง",
    meaning: "พลังงานแอคทีฟ มีไฟในการทำงาน ลาภลอย เงินทองคล่องตัว มีคู่ครองส่งเสริมฐานะ",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 10, prestige: 7, wisdom: 7, luck: 9 },
  },
  "45": {
    pair: "45",
    tier: "A+",
    scoreDelta: 20,
    category: "ปัญญาสมาธิ / มงคลรอบด้าน",
    title: "คู่เทพแห่งปัญญา ผู้รอบรู้และประสบความสำเร็จ",
    meaning: "ฉลาดหลักแหลม มีคุณธรรม การเรียนการงานเป็นเลิศ ไร้อุปสรรค ผู้ใหญ่เมตตาสุดขีด",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 8, prestige: 9, wisdom: 10, luck: 9 },
  },
  "54": {
    pair: "54",
    tier: "A+",
    scoreDelta: 20,
    category: "ปัญญาสมาธิ / มงคลรอบด้าน",
    title: "คู่สำเร็จสมปรารถนา สติปัญญานำพาความมั่งคั่ง",
    meaning: "ชีวิตมั่นคง วางแผนแม่นยำ ไม่ตกอับ มีสิ่งศักดิ์สิทธิ์คุ้มครอง เจรจาสำเร็จทุกงาน",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 8, prestige: 9, wisdom: 10, luck: 9 },
  },
  "46": {
    pair: "46",
    tier: "A+",
    scoreDelta: 19,
    category: "ค้าขาย / รวยความสุข",
    title: "คู่ค้าขายโชคดี มีความสุข วาจาเรียกทรัพย์",
    meaning: "หาเงินง่าย ใช้ชีวิตสนุก ร่าเริงแจ่มใส เจรจาปิดการขายง่าย ลูกค้าติดใจ",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 9, prestige: 6, wisdom: 8, luck: 9 },
  },
  "64": {
    pair: "64",
    tier: "A+",
    scoreDelta: 19,
    category: "ค้าขาย / รวยความสุข",
    title: "คู่สุขนิยม ทรัพย์สมบูรณ์ พูดเงินได้เงิน",
    meaning: "อ่อนหวาน มีรสนิยมดี ได้รับของขวัญของฝากบ่อย การเงินคล่องตัว มั่งคั่ง",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 9, prestige: 6, wisdom: 8, luck: 9 },
  },
  "56": {
    pair: "56",
    tier: "A+",
    scoreDelta: 20,
    category: "โภคทรัพย์สมบูรณ์ / สติและการเงิน",
    title: "คู่ทรัพย์คู่โชค รวยปัญญาและเงินทอง",
    meaning: "จัดสรรการเงินดีเยี่ยม มีสติควบคุมอารมณ์ ร่ำรวยมั่นคง มีคู่ครองดี ชีวิตอบอุ่น",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 9, prestige: 8, wisdom: 10, luck: 9 },
  },
  "65": {
    pair: "65",
    tier: "A+",
    scoreDelta: 20,
    category: "โภคทรัพย์สมบูรณ์ / สติและการเงิน",
    title: "คู่โชคลาภสมบูรณ์แบบ เงินทองไหลมาไม่ขาด",
    meaning: "เป็นคู่เลขมงคลอันดับต้นๆ ของศาสตร์ตัวเลข สุขภาพกายใจดี ความรักมั่นคง",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 9, prestige: 8, wisdom: 10, luck: 9 },
  },
  "59": {
    pair: "59",
    tier: "A+",
    scoreDelta: 19,
    category: "สิ่งศักดิ์สิทธิ์คุ้มครอง / ปัญญาญาณ",
    title: "คู่บุญบารมี สิ่งศักดิ์สิทธิ์คุ้มครอง เทคโนโลยี",
    meaning: "มีเซ้นส์สัมผัสพิเศษ แคล้วคลาดปลอดภัย มีบารมี ติดต่อต่างประเทศหรือสายไอทีเด่นมาก",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 7, prestige: 9, wisdom: 10, luck: 10 },
  },
  "95": {
    pair: "95",
    tier: "A+",
    scoreDelta: 19,
    category: "สิ่งศักดิ์สิทธิ์คุ้มครอง / ปัญญาญาณ",
    title: "คู่ปัญญาบารมี แคล้วคลาด เจริญด้วยคุณธรรม",
    meaning: "จิตใจสงบ มีศีลธรรม ผู้ใหญ่นับถือ เหมาะกับอาจารย์ แพทย์ นักบริหาร และสายมู",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 7, prestige: 9, wisdom: 10, luck: 10 },
  },
  "78": {
    pair: "78",
    tier: "A+",
    scoreDelta: 18,
    category: "มหาอำนาจ / อภิมหาเศรษฐี (กลุ่มมังกร)",
    title: "คู่บารมีมังกร คุมคนงานใหญ่ เงินก้อนยักษ์",
    meaning: "มีพรรคพวกบริวารมาก ใจใหญ่ ใจถึง เหมาะกับนักเลงการค้า เจ้าของธุรกิจ นักพัฒนาอสังหาฯ",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 6, prestige: 10, wisdom: 7, luck: 8 },
  },
  "87": {
    pair: "87",
    tier: "A+",
    scoreDelta: 18,
    category: "มหาอำนาจ / อภิมหาเศรษฐี (กลุ่มมังกร)",
    title: "คู่มังกรพลิกฟื้น พลังผู้นำเหนือคน",
    meaning: "คิดการใหญ่ กล้าได้กล้าเสีย บริหารธุรกิจขนาดใหญ่ ชนะคู่แข่งทางการค้า",
    isDangerous: false,
    energyScores: { wealth: 10, charm: 6, prestige: 10, wisdom: 7, luck: 8 },
  },
  "89": {
    pair: "89",
    tier: "A+",
    scoreDelta: 18,
    category: "บารมีอำนาจ / มังกรสากล",
    title: "คู่บารมีอำนาจ สิ่งศักดิ์สิทธิ์หนุนดวง",
    meaning: "มีอำนาจวาสนา ลูกน้องเกรงใจ ขยายธุรกิจได้ระดับสากล มีสิ่งศักดิ์สิทธิ์สายพญานาคหนุน",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 6, prestige: 10, wisdom: 8, luck: 9 },
  },
  "98": {
    pair: "98",
    tier: "A+",
    scoreDelta: 18,
    category: "บารมีอำนาจ / มังกรสากล",
    title: "คู่ผู้นำบารมี เกียรติยศชื่อเสียง",
    meaning: "เป็นผู้นำองค์กร มีเกียรติยศชื่อเสียง เป็นที่เคารพนับถือของคนหมู่มาก",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 6, prestige: 10, wisdom: 8, luck: 9 },
  },
  "99": {
    pair: "99",
    tier: "A+",
    scoreDelta: 17,
    category: "สิ่งศักดิ์สิทธิ์ / อัจฉริยะ",
    title: "คู่พลังจักรวาล แคล้วคลาด สัมผัสพิเศษ",
    meaning: "มีสัมผัสที่หก แม่นยำเรื่องลางสังหรณ์ มีความเก่งเฉพาะตัว โชคดีแบบปาฏิหาริย์",
    isDangerous: false,
    energyScores: { wealth: 7, charm: 6, prestige: 9, wisdom: 9, luck: 10 },
  },

  // === คู่มงคลระดับดี (A TIER & B TIER) ===
  "16": {
    pair: "16",
    tier: "A",
    scoreDelta: 14,
    category: "การเงินรอบคอบ / วางแผน",
    title: "คู่วางแผนการเงิน รวยเงียบ มัธยัสถ์",
    meaning: "หาเงินเก่ง คิดก่อนใช้ มีเงินเก็บเป็นกอบเป็นกำ ไม่ฟุ่มเฟือย เหมาะกับงานบริหารและบัญชี",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 7, prestige: 7, wisdom: 9, luck: 7 },
  },
  "61": {
    pair: "61",
    tier: "A",
    scoreDelta: 14,
    category: "การเงินรอบคอบ / วางแผน",
    title: "คู่จัดสรรการเงิน รายรับมั่นคง",
    meaning: "รอบคอบทางการเงิน วิเคราะห์เก่ง ไม่ประมาท มีรากฐานชีวิตมั่นคง",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 7, prestige: 7, wisdom: 9, luck: 7 },
  },
  "19": {
    pair: "19",
    tier: "A",
    scoreDelta: 15,
    category: "เกียรติยศ / ชื่อเสียง",
    title: "คู่ความโดดเด่น ผู้นำสายก้าวหน้า",
    meaning: "รักความก้าวหน้า เด่นดังในสายงาน มีความมั่นใจสูง ได้รับการยอมรับในวงสังคม",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 7, prestige: 9, wisdom: 8, luck: 8 },
  },
  "91": {
    pair: "91",
    tier: "A",
    scoreDelta: 15,
    category: "เกียรติยศ / ชื่อเสียง",
    title: "คู่ชื่อเสียง บารมีผู้นำยุคใหม่",
    meaning: "โดดเด่นมีเอกลักษณ์ ทันสมัย ก้าวหน้าเร็วกว่าคนรุ่นเดียวกัน มีวิสัยทัศน์",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 7, prestige: 9, wisdom: 8, luck: 8 },
  },
  "22": {
    pair: "22",
    tier: "A",
    scoreDelta: 13,
    category: "เสน่ห์อ่อนโยน / งานบริการ",
    title: "คู่มหาเสน่ห์สายหวาน อ่อนโยน เข้าถึงง่าย",
    meaning: "ใจดี อ่อนหวาน ผู้คนอยากเข้าใกล้ เหมาะกับงานบริการ ความงาม สปา เครื่องสำอาง",
    caution: "ระวังเรื่องความขี้เกรงใจและอารมณ์ไหวเอน",
    isDangerous: false,
    energyScores: { wealth: 7, charm: 10, prestige: 5, wisdom: 6, luck: 8 },
  },
  "23": {
    pair: "23",
    tier: "A",
    scoreDelta: 15,
    category: "มหาเสน่ห์ดึงดูด / การค้า",
    title: "คู่เสน่ห์เจ้าสำราญ ดึงดูดเพศตรงข้ามและลูกค้า",
    meaning: "เสน่ห์แรงมาก มั่นใจ ค้าขายเก่ง หาเงินคล่องตัว วาจาหยอดคำหวานเก่ง",
    caution: "ระวังเรื่องรถไฟชนกันทางความรัก",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 10, prestige: 6, wisdom: 6, luck: 8 },
  },
  "32": {
    pair: "32",
    tier: "A",
    scoreDelta: 15,
    category: "มหาเสน่ห์ดึงดูด / การค้า",
    title: "คู่เสน่ห์วาจา มนต์สะกดลูกค้า",
    meaning: "เสน่ห์ล้นเหลือ ลูกค้าติดตรึม ขายอะไรก็มีคนซื้อ มีความเซ็กซี่ในตัว",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 10, prestige: 6, wisdom: 6, luck: 8 },
  },
  "26": {
    pair: "26",
    tier: "A",
    scoreDelta: 15,
    category: "วาจาเป็นทรัพย์ / ศิลปะ",
    title: "คู่อ่อนหวาน วาจาเรียกเงินทอง",
    meaning: "พูดเพราะ น่าฟัง มีรสนิยมสูง ชอบความสวยงาม หาเงินจากงานศิลป์และค้าขายได้ดี",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 10, prestige: 5, wisdom: 7, luck: 8 },
  },
  "62": {
    pair: "62",
    tier: "A",
    scoreDelta: 15,
    category: "วาจาเป็นทรัพย์ / ศิลปะ",
    title: "คู่เจรจาเรียกทรัพย์ เสน่ห์เมตตา",
    meaning: "เข้ากับคนง่าย ได้รับความเอ็นดู มีโชคเรื่องความรักและของกำนัล",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 10, prestige: 5, wisdom: 7, luck: 8 },
  },
  "29": {
    pair: "29",
    tier: "A",
    scoreDelta: 15,
    category: "ศิลปะ / จินตนาการ / หงส์",
    title: "คู่ศิลปิน จินตนาการล้ำเลิศ ไหวพริบดี",
    meaning: "ความคิดสร้างสรรค์สูง เซ้นส์ดี รสนิยมหรูหรา งานดีไซน์ งานออนไลน์โดดเด่น",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 9, prestige: 7, wisdom: 8, luck: 8 },
  },
  "92": {
    pair: "92",
    tier: "A",
    scoreDelta: 15,
    category: "ศิลปะ / จินตนาการ / หงส์",
    title: "คู่มนต์เสน่ห์ ความคิดสร้างสรรค์",
    meaning: "หยั่งรู้อารมณ์คนเก่ง ออกแบบไอเดียใหม่ๆ ได้เสมอ งานโฆษณา อินฟลูเอนเซอร์ปังมาก",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 9, prestige: 7, wisdom: 8, luck: 8 },
  },
  "35": {
    pair: "35",
    tier: "A",
    scoreDelta: 16,
    category: "อำนาจปกครอง / ข้าราชการ",
    title: "คู่ปกครอง ทรงอำนาจบารมี ลูกน้องเคารพ",
    meaning: "มีความเด็ดขาด หนักแน่น ขยัน ผู้ใหญ่เกื้อหนุน เหมาะกับทหาร ตำรวจ ผู้บริหารโรงงาน",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 5, prestige: 10, wisdom: 8, luck: 8 },
  },
  "53": {
    pair: "53",
    tier: "A",
    scoreDelta: 16,
    category: "อำนาจปกครอง / ข้าราชการ",
    title: "คู่วินัยและอำนาจ เติบโตมั่นคง",
    meaning: "ตรงไปตรงมา เจ้านายไว้วางใจ ทำงานจริงจัง ผลงานประจักษ์ เลื่อนขั้นไว",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 5, prestige: 10, wisdom: 8, luck: 8 },
  },
  "39": {
    pair: "39",
    tier: "A",
    scoreDelta: 15,
    category: "การแข่งขัน / ชัยชนะ",
    title: "คู่นักสู้ ชัยชนะเหนือคู่แข่ง",
    meaning: "ไม่ยอมแพ้ กระตือรือร้น ชอบความท้าทาย ชนะการประมูล แข่งขันกีฬา ชิงทุนสำเร็จ",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 6, prestige: 8, wisdom: 7, luck: 9 },
  },
  "93": {
    pair: "93",
    tier: "A",
    scoreDelta: 15,
    category: "การแข่งขัน / ชัยชนะ",
    title: "คู่พลังชัยชนะ คล่องแคล่วว่องไว",
    meaning: "พลังล้นเหลือ ตัดสินใจรวดเร็ว ชนะอุปสรรค เหมาะกับงานขายเชิงรุกและนักกีฬา",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 6, prestige: 8, wisdom: 7, luck: 9 },
  },
  "49": {
    pair: "49",
    tier: "A",
    scoreDelta: 16,
    category: "เทคโนโลยี / ภาษาต่างประเทศ",
    title: "คู่ไอที สมองไว ติดต่อต่างประเทศ",
    meaning: "หัวไว เรียนรู้เทคโนโลยีเร็ว ติดต่องานข้ามชาติ งานดิจิทัล โค้ดดิ้ง สื่อสารรวดเร็ว",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 7, prestige: 7, wisdom: 10, luck: 8 },
  },
  "94": {
    pair: "94",
    tier: "A",
    scoreDelta: 16,
    category: "เทคโนโลยี / ภาษาต่างประเทศ",
    title: "คู่ปัญญาดิจิทัล วิสัยทัศน์ล้ำยุค",
    meaning: "มีเซ้นส์ด้านข้อมูลและเทรนด์ใหม่ๆ สื่อสารภาษาต่างประเทศได้คล่องแคล่ว",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 7, prestige: 7, wisdom: 10, luck: 8 },
  },
  "55": {
    pair: "55",
    tier: "A",
    scoreDelta: 16,
    category: "มหาปัญญา / ธรรมะ",
    title: "คู่ปราชญ์ จิตใจสงบ มีความสุข",
    meaning: "สุขุม มีเหตุผล สมาธิดีเลิศ ชีวิตร่มเย็น ปลอดภัย เหมาะกับครูบาอาจารย์ นักวิจัย",
    caution: "อาจจะเรื่อยๆ ไม่กระตือรือร้นหาเงินก้อนใหญ่ เหมาะกับคนชอบความสงบ",
    isDangerous: false,
    energyScores: { wealth: 7, charm: 7, prestige: 8, wisdom: 10, luck: 9 },
  },
  "66": {
    pair: "66",
    tier: "A",
    scoreDelta: 15,
    category: "สำราญใจ / ร่ำรวยสุข",
    title: "คู่สุขนิยม เงินทองและเสน่ห์ล้นเหลือ",
    meaning: "รักความสบาย สวยหรู รวยเสน่ห์ หาเงินได้ใช้เงินคล่อง มีความสุขในชีวิต",
    caution: "ระวังใช้จ่ายฟุ่มเฟือยตามใจตัวเอง",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 10, prestige: 5, wisdom: 6, luck: 8 },
  },
  "69": {
    pair: "69",
    tier: "A",
    scoreDelta: 16,
    category: "หมุนเงินคล่อง / แฟชั่นบันเทิง",
    title: "คู่เงินทองหมุนเวียน รสนิยมนำเทรนด์",
    meaning: "เงินสะพัดไม่ขาดมือ โชคลาภบ่อย มีรสนิยมดี งานแฟชั่น อสังหาฯ และวงการบันเทิงเด่น",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 9, prestige: 6, wisdom: 7, luck: 9 },
  },
  "96": {
    pair: "96",
    tier: "A",
    scoreDelta: 16,
    category: "หมุนเงินคล่อง / แฟชั่นบันเทิง",
    title: "คู่ดึงดูดทรัพย์ ลาภลอย เงินหมุน",
    meaning: "มีเสน่ห์ มีสไตล์ หาเงินง่ายจากหลายช่องทาง ชีวิตมีสีสันและโชคลาภ",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 9, prestige: 6, wisdom: 7, luck: 9 },
  },

  // === คู่ต้องห้าม / คู่อัปมงคล / ดาวบาปเคราะห์ (DANGEROUS PAIRS - F TIER) ===
  "13": {
    pair: "13",
    tier: "F",
    scoreDelta: -30,
    category: "อุบัติเหตุ / ผ่าตัด",
    title: "คู่ดาวผ่าตัด อุบัติเหตุรุนแรง อารมณ์ร้อน",
    meaning: "มักมีเกณฑ์ผ่าตัด เลือดตกยางออก ใจร้อนวู่วาม ทะเลาะวิวาท แตกหักกะทันหัน",
    caution: "❌ เลขต้องห้ามเด็ดขาด ไม่แนะนำให้มีในเบอร์โทรศัพท์",
    isDangerous: true,
    energyScores: { wealth: 2, charm: 1, prestige: 3, wisdom: 2, luck: 1 },
  },
  "31": {
    pair: "31",
    tier: "F",
    scoreDelta: -30,
    category: "อุบัติเหตุ / ผ่าตัด",
    title: "คู่อุบัติเหตุ การแตกหัก เสียเลือดเนื้อ",
    meaning: "เกิดเหตุไม่คาดฝัน เจ็บตัว อารมณ์รุนแรง ขัดแย้งกับผู้อื่นได้ง่าย",
    caution: "❌ เลขต้องห้ามเด็ดขาด",
    isDangerous: true,
    energyScores: { wealth: 2, charm: 1, prestige: 3, wisdom: 2, luck: 1 },
  },
  "18": {
    pair: "18",
    tier: "F",
    scoreDelta: -28,
    category: "ถูกหักหลัง / คดีความ",
    title: "คู่ดาวถูกหักหลัง ปิดทองหลังพระ โดนโกง",
    meaning: "มักถูกคนสนิทหักหลัง ทำคุณคนไม่ขึ้น มีปัญหากับผู้ใหญ่ เสี่ยงคดีความ โดนใส่ร้าย",
    caution: "❌ เลขอันตราย ควรหลีกเลี่ยง",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 2, prestige: 4, wisdom: 3, luck: 1 },
  },
  "81": {
    pair: "81",
    tier: "F",
    scoreDelta: -28,
    category: "ถูกหักหลัง / คดีความ",
    title: "คู่ทรยศหักหลัง ภาระหนี้สิน เอกสารมีปัญหา",
    meaning: "ถูกโกงเงิน เสียชื่อเสียง ค้ำประกันเดือดร้อน มีศัตรูในที่ลับ",
    caution: "❌ เลขอันตราย ควรหลีกเลี่ยง",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 2, prestige: 4, wisdom: 3, luck: 1 },
  },
  "07": {
    pair: "07",
    tier: "F",
    scoreDelta: -25,
    category: "ทุกข์ระทม / โรคเรื้อรัง",
    title: "คู่ดาวอมทุกข์ แบกรับภาระ เครียดสะสม",
    meaning: "เหน็ดเหนื่อยแสนสาหัส ทำงานหนักแต่ได้ผลตอบแทนน้อย เครียด ไมเกรน โรคกระดูก",
    caution: "❌ เลขนำพาความเหน็ดเหนื่อยและทุกข์ใจ",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 1, prestige: 2, wisdom: 3, luck: 1 },
  },
  "70": {
    pair: "70",
    tier: "F",
    scoreDelta: -25,
    category: "ทุกข์ระทม / โรคเรื้อรัง",
    title: "คู่ดาวความกดดัน โรคภัยเงียบ ปัญหายืดเยื้อ",
    meaning: "ชีวิตมีแต่อุปสรรค ยืดเยื้อแก้ไม่ตก โดนกดดันจากรอบข้าง",
    caution: "❌ เลขนำพาความทุกข์ระทม",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 1, prestige: 2, wisdom: 3, luck: 1 },
  },
  "08": {
    pair: "08",
    tier: "F",
    scoreDelta: -25,
    category: "อบายมุข / เสียทรัพย์",
    title: "คู่ดาวราหูครอบงำ หลงมัวเมา เงินรั่วไหล",
    meaning: "ถูกหลอกลวง มัวเมาอบายมุข เสียเงินก้อนโต การเงินติดลบ คบเพื่อนพาล",
    caution: "❌ เลขเสี่ยงเสียทรัพย์และโดนหลอก",
    isDangerous: true,
    energyScores: { wealth: 2, charm: 2, prestige: 3, wisdom: 2, luck: 2 },
  },
  "80": {
    pair: "80",
    tier: "F",
    scoreDelta: -25,
    category: "อบายมุข / เสียทรัพย์",
    title: "คู่ความลุ่มหลง ปัญหาหนี้สินเรื้อรัง",
    meaning: "เก็บเงินไม่อยู่ หนี้สินพอกพูน หูเบา เชื่อคนง่าย มีเรื่องเดือดร้อนใจ",
    caution: "❌ เลขเสี่ยงปัญหาหนี้สิน",
    isDangerous: true,
    energyScores: { wealth: 2, charm: 2, prestige: 3, wisdom: 2, luck: 2 },
  },
  "03": {
    pair: "03",
    tier: "F",
    scoreDelta: -22,
    category: "อารมณ์ร้อน / ทะเลาะวิวาท",
    title: "คู่ดาวใจร้อน ระเบิดอารมณ์ ขัดแย้ง",
    meaning: "ควบคุมอารมณ์ไม่ได้ พูดจาขวานผ่าซาก เกิดอุบัติเหตุจากการประมาท ทะเลาะคนรอบข้าง",
    caution: "❌ เลขอารมณ์เดือด",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 1, prestige: 3, wisdom: 2, luck: 2 },
  },
  "30": {
    pair: "30",
    tier: "F",
    scoreDelta: -22,
    category: "อารมณ์ร้อน / ทะเลาะวิวาท",
    title: "คู่วิวาทะ แตกหักกับมิตร",
    meaning: "ใจร้อน ปะทะบ่อย ความสัมพันธ์แตกแยก",
    caution: "❌ เลขก่อวิวาท",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 1, prestige: 3, wisdom: 2, luck: 2 },
  },
  "37": {
    pair: "37",
    tier: "F",
    scoreDelta: -26,
    category: "วิบากกรรม / แตกหักรุนแรง",
    title: "คู่ดาวเสี้ยนหนาม วิบากกรรม ความสูญเสีย",
    meaning: "ปัญหาประดังประเด เหนื่อยทั้งชีวิต ครอบครัวแตกแยก การเงินวิกฤต",
    caution: "❌ คู่อัปมงคลรุนแรง",
    isDangerous: true,
    energyScores: { wealth: 2, charm: 1, prestige: 2, wisdom: 2, luck: 1 },
  },
  "73": {
    pair: "73",
    tier: "F",
    scoreDelta: -26,
    category: "วิบากกรรม / แตกหักรุนแรง",
    title: "คู่ความเจ็บปวด เสียทรัพย์และคู่ครอง",
    meaning: "เจอแต่คนเอารัดเอาเปรียบ ทุกข์ใจเรื่องเงินและคนรัก",
    caution: "❌ คู่อัปมงคลรุนแรง",
    isDangerous: true,
    energyScores: { wealth: 2, charm: 1, prestige: 2, wisdom: 2, luck: 1 },
  },
  "27": {
    pair: "27",
    tier: "F",
    scoreDelta: -20,
    category: "หนี้สิน / ผิดหวังความรัก",
    title: "คู่ดาวพลัดพราก หนี้สินรุงรัง ช้ำรัก",
    meaning: "หมุนเงินไม่ทัน เป็นหนี้สิน มีเรื่องรักสามเส้า ผิดหวังซ้ำซาก",
    caution: "❌ เลขเสี่ยงปัญหาหนี้สินและความรัก",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 4, prestige: 3, wisdom: 3, luck: 2 },
  },
  "72": {
    pair: "72",
    tier: "F",
    scoreDelta: -20,
    category: "หนี้สิน / ผิดหวังความรัก",
    title: "คู่หนี้สินพลัดพราก ความกดดันการเงิน",
    meaning: "หาเงินได้แต่มีคนมาแย่งชิงหรือมีเหตุต้องจ่ายก้อนโต",
    caution: "❌ เลขเสี่ยงปัญหาการเงิน",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 4, prestige: 3, wisdom: 3, luck: 2 },
  },
  "00": {
    pair: "00",
    tier: "F",
    scoreDelta: -25,
    category: "ว่างเปล่า / โดดเดี่ยว",
    title: "คู่ดาวมฤตยูคู่ สูญเปล่า โดดเดี่ยว",
    meaning: "ทำอะไรมักสูญเปล่า สันโดษเกินไป ปลีกวิเวก สุขภาพเสื่อมโทรม",
    caution: "❌ ไม่เหมาะกับการใช้ในชีวิตประจำวันและการค้า",
    isDangerous: true,
    energyScores: { wealth: 1, charm: 1, prestige: 2, wisdom: 4, luck: 2 },
  },
  "06": {
    pair: "06",
    tier: "F",
    scoreDelta: -20,
    category: "รักซ้อน / เงินรั่ว",
    title: "คู่ดาวรักซ้อน กระเป๋าเงินรั่ว",
    meaning: "ใช้เงินตามอารมณ์ เก็บเงินไม่อยู่ มีปัญหาเรื่องรักซ้อน ชู้สาว",
    caution: "❌ ระวังปัญหาความรักและการเงินรั่ว",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 6, prestige: 3, wisdom: 2, luck: 2 },
  },
  "60": {
    pair: "60",
    tier: "F",
    scoreDelta: -20,
    category: "รักซ้อน / เงินรั่ว",
    title: "คู่ความลุ่มหลงในกิเลส เงินทองรั่วไหล",
    meaning: "ควบคุมกิเลสยาก ใช้เงินมือเติบ ความรักมักซ่อนเร้น",
    caution: "❌ ระวังเรื่องการเงินและความรัก",
    isDangerous: true,
    energyScores: { wealth: 3, charm: 6, prestige: 3, wisdom: 2, luck: 2 },
  },
  "02": {
    pair: "02",
    tier: "D",
    scoreDelta: -15,
    category: "ใจอ่อน / โดนหลอก",
    title: "คู่เสน่ห์ลุ่มหลง อ่อนไหวเกินเหตุ",
    meaning: "ขี้สงสาร หูเบา มักโดนเอาเปรียบเรื่องเงินและความรัก",
    caution: "⚠️ ต้องระวังคนรอบข้าง",
    isDangerous: false,
    energyScores: { wealth: 4, charm: 7, prestige: 3, wisdom: 3, luck: 4 },
  },
  "20": {
    pair: "20",
    tier: "D",
    scoreDelta: -15,
    category: "ใจอ่อน / โดนหลอก",
    title: "คู่เสน่ห์ซ่อนเร้น อารมณ์แปรปรวน",
    meaning: "อารมณ์น้อยใจง่าย มีเรื่องปิดบังซ่อนเร้น",
    caution: "⚠️ ระวังเรื่องความลับ",
    isDangerous: false,
    energyScores: { wealth: 4, charm: 7, prestige: 3, wisdom: 3, luck: 4 },
  },
  "04": {
    pair: "04",
    tier: "D",
    scoreDelta: -12,
    category: "วาจาปากไว / เสียคำพูด",
    title: "คู่วาจาหลุดปาก เอกสารผิดพลาด",
    meaning: "พูดเร็วเกินคิด สัญญาผิดพลาด ข้อมูลตกหล่น",
    isDangerous: false,
    energyScores: { wealth: 4, charm: 4, prestige: 3, wisdom: 5, luck: 4 },
  },
  "40": {
    pair: "40",
    tier: "D",
    scoreDelta: -12,
    category: "วาจาปากไว / เสียคำพูด",
    title: "คู่สื่อสารเข้าใจคลาดเคลื่อน",
    meaning: "มักสื่อสารไม่ตรงกับใจ ถูกเข้าใจผิดง่าย",
    isDangerous: false,
    energyScores: { wealth: 4, charm: 4, prestige: 3, wisdom: 5, luck: 4 },
  },
  "05": {
    pair: "05",
    tier: "C",
    scoreDelta: -5,
    category: "ยึดมั่น / คิดมาก",
    title: "คู่ดื้อรั้น ยึดติดความคิดตนเอง",
    meaning: "มีหลักการสูงเกินไป ไม่ค่อยยืดหยุ่น คิดเยอะจนเครียด",
    isDangerous: false,
    energyScores: { wealth: 5, charm: 3, prestige: 6, wisdom: 7, luck: 5 },
  },
  "50": {
    pair: "50",
    tier: "C",
    scoreDelta: -5,
    category: "ยึดมั่น / คิดมาก",
    title: "คู่ความคิดมาก สันโดษทางปัญญา",
    meaning: "ชอบอยู่คนเดียว ชอบศึกษาเรื่องลึกซึ้ง แต่อาจขาดมนุษยสัมพันธ์เชิงพาณิชย์",
    isDangerous: false,
    energyScores: { wealth: 5, charm: 3, prestige: 6, wisdom: 7, luck: 5 },
  },
  "09": {
    pair: "09",
    tier: "B",
    scoreDelta: 8,
    category: "ลางสังหรณ์ / ต่างแดน",
    title: "คู่เซ้นส์แรง แคล้วคลาด ต่างถิ่นต่างแดน",
    meaning: "สัมผัสสิ่งลี้ลับได้ เหมาะกับสายมู สายเทคโนโลยี หรือคนทำงานไกลบ้าน",
    isDangerous: false,
    energyScores: { wealth: 6, charm: 4, prestige: 6, wisdom: 8, luck: 9 },
  },
  "90": {
    pair: "90",
    tier: "B",
    scoreDelta: 8,
    category: "ลางสังหรณ์ / ต่างแดน",
    title: "คู่สิ่งศักดิ์สิทธิ์คุ้มครอง งานเบื้องหลัง",
    meaning: "แคล้วคลาด ทำงานเบื้องหลังสำเร็จดี",
    isDangerous: false,
    energyScores: { wealth: 6, charm: 4, prestige: 6, wisdom: 8, luck: 9 },
  },
  "77": {
    pair: "77",
    tier: "D",
    scoreDelta: -10,
    category: "งานหนัก / แบกรับ",
    title: "คู่เสาร์คู่ งานหนักยิ่งยวด อดทนสูง",
    meaning: "เหนื่อยมาก แบกรับภาระทั้งตระกูล เหมาะกับคนสู้ชีวิตจริงๆ",
    isDangerous: false,
    energyScores: { wealth: 5, charm: 2, prestige: 6, wisdom: 5, luck: 3 },
  },
  "88": {
    pair: "88",
    tier: "B",
    scoreDelta: 10,
    category: "กล้าได้กล้าเสีย / สีเทา",
    title: "คู่ราหูคู่ เงินหมุนเร็ว กล้าได้กล้าเสีย",
    meaning: "ใจใหญ่ กล้าลงทุน ทำธุรกิจกลางคืน ผับบาร์ บิตคอยน์ การเสี่ยงโชค",
    caution: "ต้องมีเลขปัญญาควบคุม",
    isDangerous: false,
    energyScores: { wealth: 9, charm: 5, prestige: 8, wisdom: 4, luck: 8 },
  },
  "11": {
    pair: "11",
    tier: "C",
    scoreDelta: 0,
    category: "ทิฐิสูง / มั่นใจเกิน",
    title: "คู่อาทิตย์คู่ มั่นใจตนเองสูง เด่นจนคนอิจฉา",
    meaning: "เก่ง โดดเด่น แต่เหนื่อยเพราะต้องทำเองทุกอย่าง คนมักอิจฉา",
    isDangerous: false,
    energyScores: { wealth: 6, charm: 4, prestige: 8, wisdom: 6, luck: 5 },
  },
  "33": {
    pair: "33",
    tier: "C",
    scoreDelta: -2,
    category: "พลังงานสูง / อารมณ์ร้อน",
    title: "คู่อังคารคู่ พลังล้นเหลือ ใจร้อน คล่องแคล่ว",
    meaning: "ขยัน อดทน สู้งานหนัก แต่ใจร้อน วู่วาม มักเกิดเรื่องทะเลาะได้ง่าย",
    isDangerous: false,
    energyScores: { wealth: 7, charm: 4, prestige: 7, wisdom: 4, luck: 5 },
  },
  "44": {
    pair: "44",
    tier: "A",
    scoreDelta: 14,
    category: "วาจาคล่อง / ข้อมูลข่าวสาร",
    title: "คู่พุธคู่ สื่อสารฉับไว ติดต่อเร็ว",
    meaning: "พูดเก่ง มนุษยสัมพันธ์ดี ค้าขายออนไลน์ดี สื่อสารไม่หยุดหย่อน",
    isDangerous: false,
    energyScores: { wealth: 8, charm: 8, prestige: 6, wisdom: 8, luck: 7 },
  },
};

// Fallback generator for any unlisted pair 00-99
export function getPairRule(pair: string): PairRule {
  if (PAIR_RULES_MAP[pair]) {
    return PAIR_RULES_MAP[pair];
  }
  
  // Default evaluation for uncommon neutral pairs
  return {
    pair,
    tier: "C",
    scoreDelta: 5,
    category: "ทั่วไป",
    title: `คู่เลข ${pair}`,
    meaning: `พลังงานระดับปานกลาง มีความเป็นกลางในการใช้งาน`,
    isDangerous: false,
    energyScores: { wealth: 5, charm: 5, prestige: 5, wisdom: 5, luck: 5 },
  };
}
